// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeSK7MMrPfqENV6wzPsjru8DS5Uu3yNq4',
    appId: '1:58473386460:web:783f1208666b805e0ebf19',
    messagingSenderId: '58473386460',
    projectId: 'fieldtaskapp',
    authDomain: 'fieldtaskapp.firebaseapp.com',
    storageBucket: 'fieldtaskapp.firebasestorage.app',
    measurementId: 'G-DHTCFLY76B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaAkZUQh83P1cwal_vDw-QzZbAnohWymY',
    appId: '1:58473386460:android:32a17dd301d5ebc20ebf19',
    messagingSenderId: '58473386460',
    projectId: 'fieldtaskapp',
    storageBucket: 'fieldtaskapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-zbgdPCyIcZTjRNkf5VauN9qic_ktHf0',
    appId: '1:58473386460:ios:3d3fe0af770e04510ebf19',
    messagingSenderId: '58473386460',
    projectId: 'fieldtaskapp',
    storageBucket: 'fieldtaskapp.firebasestorage.app',
    iosBundleId: 'com.example.fieldTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-zbgdPCyIcZTjRNkf5VauN9qic_ktHf0',
    appId: '1:58473386460:ios:3d3fe0af770e04510ebf19',
    messagingSenderId: '58473386460',
    projectId: 'fieldtaskapp',
    storageBucket: 'fieldtaskapp.firebasestorage.app',
    iosBundleId: 'com.example.fieldTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeSK7MMrPfqENV6wzPsjru8DS5Uu3yNq4',
    appId: '1:58473386460:web:6825d8ef3377c7770ebf19',
    messagingSenderId: '58473386460',
    projectId: 'fieldtaskapp',
    authDomain: 'fieldtaskapp.firebaseapp.com',
    storageBucket: 'fieldtaskapp.firebasestorage.app',
    measurementId: 'G-CNPNBCVS08',
  );
}
